import { Exercise } from "../types";

export const exercises: Exercise[] = [
  {
    name: "Rickshaw Carry",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/rickshaw-carry",
    targetMuscle: "Forearms",
    equipment: "Other",
    rating: 9.6,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/742/Male/m/742_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/742/Male/m/742_2.jpg",
    ],
    type: "Strongman",
    level: "Beginner",
    description: [],
    benefits: [],
  },
  {
    name: "One-Arm Medicine Ball Slam",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/one-arm-medicine-ball-slam",
    targetMuscle: "Abdominals",
    equipment: "Medicine Ball",
    rating: 9.5,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/2081/Male/m/2081_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/2081/Male/m/2081_2.jpg",
    ],
    type: "Strength",
    level: "Intermediate",
    description: [
      "The single-arm medicine ball slam is an explosive exercise that targets numerous muscles, but primarily the core and lats (latissimus dorsi). You won't be able to slam the ball nearly as hard as you can with two arms, but the single-arm version provides the same type of coordination and power challenge. It can be performed for time or reps in an upper body or conditioning-focused workout.",
    ],
    benefits: [
      "Works the core, lats, and shoulders",
      "Pairs with strength or muscle-focused movements to make a circuit more metabolically taxing",
      "Burns significant calories if performed for reps",
    ],
  },
  {
    name: "Weighted Pull Ups",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/weighted-pull-ups",
    targetMuscle: "Lats",
    equipment: "Other",
    rating: 9.5,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/928/Male/m/928_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/928/Male/m/928_2.jpg",
    ],
    type: "Strength",
    level: "Intermediate",
    description: [
      "The weighted pull-up is a more advanced variation of the pull-up exercise, in which the lifter adds extra weight to their body. Options for adding weight include a dip belt, weighted vest, chains, a dumbbell placed between the feet or legs, or looping a kettlebell over the foot. Like other pull-up variations, the weighted pull-up builds strength and muscle in the upper back, biceps, and core.",
    ],
    benefits: [
      "Strengthens the muscles of the lats (latissimus dorsi), biceps, upper back, core, and grip",
      "Allows you to train pull-ups in lower strength-focused rep ranges (e.g., sets of 3-5 reps) if you can do many reps",
      "Can help boost your overall pull-up numbers",
      "Heavy, low-rep sets activate different types of muscle fibers, potentially leading to muscle and strength gains",
    ],
  },
  {
    name: "Atlas Stones",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/atlas-stones",
    targetMuscle: "Lower Back",
    equipment: "Other",
    rating: 9.5,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/659/Male/m/659_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/659/Male/m/659_2.jpg",
    ],
    type: "Strongman",
    level: "Beginner",
    description: [],
    benefits: [],
  },
  {
    name: "Side Laterals to Front Raise",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/side-laterals-to-front-raise-",
    targetMuscle: "Shoulders",
    equipment: "Dumbbell",
    rating: 9.5,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/1791/Male/m/1791_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/1791/Male/m/1791_2.jpg",
    ],
    type: "Strength",
    level: "Intermediate",
    description: [
      "The dumbbell lateral to front raise is a dumbbell complex that combines two exercises that build and strengthen the middle deltoids and the anterior deltoids of the shoulders. It is usually performed one rep of each movement at a time, although you could perform more reps of each, or increase the reps in successive rounds (e.g., 1 rep in round 1, 2 reps in round 2, etc.). No matter how you perform it, it targets both the anterior and medial deltoids, making it a great time-efficient shoulder burnout or accessory movement on an upper-body day.",
    ],
    benefits: [
      "Builds size in shoulders",
      "Prolonged muscle time under tension",
      "Great burnout on shoulder day or time-efficient shoulder pump in any workout",
    ],
  },
  {
    name: "Wrist Rotations with Straight Bar",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/wrist-rotations-with-straight-bar",
    targetMuscle: "Forearms",
    rating: 9.5,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/1691/Male/m/1691_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/1691/Male/m/1691_2.jpg",
    ],
    type: "Strength",
    level: "Intermediate",
    description: [
      "The straight-bar wrist roll-up is a movement targeting the muscles of the forearms and hands. It is normally performed in high reps, for time, or simply to failure as a burnout for the lower arms. If shoulder fatigue limits your ability to perform the movement, it can be done with the barbell resting in a rack.",
    ],
    benefits: [
      "Builds hand and wrist strength",
      "Builds forearm size and strength",
      "Doesn't require unique equipment",
      "If grip strength is a limitation, lifting straps allow heavier loading",
    ],
  },
  {
    name: "Barbell Glute Bridge",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/barbell-glute-bridge",
    targetMuscle: "Glutes",
    equipment: "Barbell",
    rating: 9.4,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/662/Male/m/662_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/662/Male/m/662_2.jpg",
    ],
    type: "Powerlifting",
    level: "Intermediate",
    description: [
      "The barbell glute bridge is popular exercise targeting the muscles of the glutes and hamstrings. It can be done as a strength movement on its own, as an activation drill or warm-up for lower body training, or as a burnout at the end of a lower-body workout.",
    ],
    benefits: [
      "Strengthens the glutes, hamstrings, and quads",
      "Allows you to track and periodize weights more than using a band does",
      "Builds strength that carries over into squats, deadlifts, and other movements",
      "Great warm-up or glute activation drill to do any time",
    ],
  },
  {
    name: "Clean and Press",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/clean-and-press",
    targetMuscle: "Shoulders",
    equipment: "Barbell",
    rating: 9.4,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/864/Male/m/864_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/864/Male/m/864_2.jpg",
    ],
    type: "Strength",
    level: "Intermediate",
    description: [
      "The clean and press is a full-body lift comprised of two movements: the clean, where the bar is pulled from the floor and caught in the front rack position in three pulls or phases, followed by the overhead press. Decades ago, it was contested in the Olympics. Today, it remains a worthy centerpiece of a power and strength training program, and has full-body benefits when done for low reps as well as moderate to high reps.",
    ],
    benefits: [
      "Trains speed and power for athletic performance",
      "Cleaning between each rep of multiple presses is a strength and conditioning challenge like no other",
      "Great move for full-body strength and power",
    ],
  },
  {
    name: "Farmer's Walk",
    img: "https://artifacts.bbcomcdn.com/@bbcom/exercises-app//img/1.png",
    url: "/exercises/farmers-walk",
    targetMuscle: "Forearms",
    equipment: "Other",
    rating: 9.4,
    imgs: [
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/682/Male/m/682_1.jpg",
      "https://www.bodybuilding.com/exercises/exerciseImages/sequences/682/Male/m/682_2.jpg",
    ],
    type: "Strongman",
    level: "Intermediate",
    description: [
      "The dumbbell farmer's walk or carry is an exercise with roots in competitive strongman training, but which is also popular in CrossFit and functional training. It can be a challenging finisher to any workout, or work well in fat-loss circuit training or as an accessory movement to heavy lifts like the deadlift.",
    ],
    benefits: [
      "Strengthens and challenges the grip, core, traps, upper back, shoulders, and legs",
      "Serious cardiovascular challenge and calorie burn",
      "Less complex to learn and perform properly than many other popular strength movements",
      "Builds muscular coordination and mental toughness in addition to strength and muscle",
      "If grip strength is a limiting factor, lifting straps can still enable you to use heavy weights",
    ],
  },
];
